---
- name : Configure Docker on EC2 Instances
  hosts : 172.31.94.98
  become: true
  connection : ssh
  tasks :
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root

  - name: remove container
    command: sudo docker rm insure-me

  - name: Deploy Docker Container
    command: docker tag insure-me subham742/insure-me:latest
    command: docker run -itd -p 8082:8081 subham742/insure-me:latest
    become : yes
    become_user : root
